global using HospitalSystem.Core.Entities;
global using HospitalSystem.Core.IRepository;
global using HospitalSystem.Infrastructure.Data;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;