global using Hospital_Management_Project.ViewModels;
global using HospitalSystem.Application.Interfaces;
global using HospitalSystem.Infrastructure.Services;
global using HospitalSystem.Persistance.Data;
global using HospitalSystem.Persistance.UnitOfWork;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using System.Diagnostics;
using HospitalSystem.Application.Services;
using Microsoft.AspNetCore.Mvc;
using HospitalSystem.Core.Entities;